print('True:',True)
print('False:',False)
print('3>2:',3>2)
print('3>5:',3>5)
print('True and True:',True and True)
print('True and False:',True and False)
print('not True:',not True)
print('not 1>2:',not 1>2)
